### ISSUE TITLE
Issues with windows

### ISSUE THREAD

**Issue by BHare1985** [dcodeIO/doco#1]
Is this not made for windows?

I couldn't get it to work off the bat, command prompt kept saying cannot find specified path. A bit of research shows your doco.cmd that was created was using references like `/usr/env/node` which don't exist in windows. I changed the cmd to

```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\node_modules\doco\bin\doco" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node "%~dp0\node_modules\doco\bin\doco" %*
)
```

Which atleast got it to execute the doco file this time when executing the `doco --gen=markdown app.js > app.md`  but then 

```
if (argv.length < 1) {
        ^
TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (C:\Users\Adminstrator.Alienware\AppData\Roaming\npm\n
ode_modules\doco\bin\doco:13:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

So I am giving up for now.

**Comment by luileito** [comment]
See issue #2
